name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Animated Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ramdev1470
          outputs: |
            dist/github-contribution-grid-snake.gif?color_snake=#00A8FF&color_dots=#161B22,#0D47A1,#1677FF,#00A8FF,#00E5FF&color_background=#050B18

      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v5
        with:
          build_dir: dist
          target_branch: output
          commit_message: "Update animated contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
